config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "apps#index"

  resources :upstreams
  resources :apps, only: %i[index create update destroy]
  resources :vanities, only: %i[index create destroy]
  resources :regexes, only: %i[index create update destroy]
  resources :users, only: %i[index update destroy] do
    collection do
      get :no_access
    end
  end

  get "monitors/lb" => "monitors#lb"

  resource :sessions, only: %i[new destroy]
  get "auth/oktaoauth/callback", to: "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout, :via => [:get, :post, :delete]
end

app/models/upstream.rb
# frozen_string_literal: true

class Upstream
  attr_reader :pattern, :target, :redis

  TARGETS = {"Cru WordPress": "WP_ADDR",
             "WordPress VIP": "VIP_ADDR",
             Storylines: "STORYLINES_ADDR",
             "Cru.org (Default)": "DEFAULT_PROXY_TARGET"}.freeze

  def initialize(pattern, target = nil)
    @redis = redis || Redis.current
    raise Index::NoredisInstance unless @redis

    @pattern = pattern
    @existing_target = Upstream.hash[pattern]
    @target = if @existing_target
      # Update if values were passed in. otherwise return existing
      target || @existing_target
    else
      target
    end

    self
  end

  def save
    unless @existing_target
      AuditEntry.create!(change_type: "add_upstream",
        key: upstream_key,
        to_value: target,
        user_id: Thread.current[:user_id])
    end
    if @existing_target && target != @existing_target
      AuditEntry.create!(change_type: "update_upstream",
        key: upstream_key,
        from_value: @existing_target,
        to_value: target,
        user_id: Thread.current[:user_id])
    end
    redis.hset(upstream_key, pattern, target)
  end

  def destroy
    redis.hdel(upstream_key, pattern)
    AuditEntry.create!(change_type: "remove_upstream",
      key: upstream_key,
      from_value: target,
      user_id: Thread.current[:user_id])
  end

  def self.all
    hash.sort.collect { |k, v| Upstream.new(k, v) }
  end

  def self.hash
    Redis.current.hgetall(upstream_key)
  end

  def created_at
    create_audit.try(:created_at)
  end

  def created_by
    create_audit.try(:user)
  end

  def updated_at
    update_audit.try(:created_at)
  end

  def updated_by
    update_audit.try(:user)
  end

  def create_audit
    @create_audit ||= AuditEntry.includes(:user).find_by(change_type: "add_upstream", key: upstream_key)
  end

  def update_audit
    @update_audit ||= AuditEntry.includes(:user)
      .where(change_type: "update_upstream", key: upstream_key)
      .order("created_at desc").first
  end

  def self.upstream_key
    "upstreams"
  end

  def upstream_key
    Upstream.upstream_key
  end

  def to_partial_path
    "upstream"
  end
end

app/controllers/upstreams_controller.rb
# frozen_string_literal: true

class UpstreamsController < ApplicationController
  def index
    @upstreams = Upstream.all
  end

  def update
    upstream = Redirect.new(Base64.decode64(params[:id]), params["target"])
    upstream.save

    redirect_to upstreams_path
  end

  def create
    upstream = Upstream.new(params[:path], params[:target])
    upstream.save

    redirect_to upstreams_path
  end

  def destroy
    upstream = Upstream.new(Base64.decode64(params[:id]))
    upstream.destroy

    redirect_to upstreams_path
  end
end

app/helpers/upstreams_helper.rb
# frozen_string_literal: true

module UpstreamsHelper
end

app/views/upstreams/_upstream.html.erb
<tr>
  <td><%= upstream.pattern %></td>
  <td><%= Upstream::TARGETS.key(upstream.target) %></td>
  <td>
    <%= form_tag upstream_path(Base64.encode64(upstream.pattern)), method: :delete,
                 data: { confirm: "Are you sure you want to remove #{upstream.pattern}?" } do %>
        <button>remove</button>
    <% end %>
  </td>
</tr>

app/views/upstreams/index.html.erb
<h2>Upstreams</h2>
<div>
    <%= form_tag upstreams_path, id: 'add_upstream_form' do %>
    <input class="path" name="path" placeholder="URL Pattern" required minlength="6" />
      <select id="new_target" class="target" name="target" data-placeholder="Choose a target">
        <% Upstream::TARGETS.each do |name, constant| %>
            <option value="<%= constant %>"><%= name %></option>
        <% end %>
      </select>
      <button>Add Upstream</button>
    <% end %>
</div>
<div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>URL Pattern</th>
          <th>Target</th>
        </tr>
      </thead>
      <tbody>
        <%= render @upstreams %>
      </tbody>
    </table>
</div>