config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "apps#index"

  resources :upstreams
  resources :apps, only: %i[index create update destroy]
  resources :vanities, only: %i[index create destroy]
  resources :regexes, only: %i[index create update destroy]
  resources :users, only: %i[index update destroy] do
    collection do
      get :no_access
    end
  end

  get "monitors/lb" => "monitors#lb"

  resource :sessions, only: %i[new destroy]
  get "auth/oktaoauth/callback", to: "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout, :via => [:get, :post, :delete]
end

app/views/apps/_app.html.erb
<tr>
  <td>
    <%= app.name %>

    <%= form_tag app_path(app.name), method: :delete,
                 data: { confirm: "Are you sure you want to remove #{app.name}?" } do %>
        <button>remove app</button>
    <% end %>
  </td>

  <td>
    <%= form_tag app_path(app.name), :class => "maintenance_form", :method => :put, :remote => true do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <label>Maintenance Mode</label>
        <input name="maintenance" type="hidden" value="0"/>
        <%= check_box_tag('maintenance', '1', app.maintenance, class: 'maintenance') %>
    <% end %>
  </td>

  <td>
    <%= form_tag app_path(app.name), :class => "dependencies_form", :method => :put, :remote => true do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <label>Dependent systems</label>
        <br>
        <select id="<%= app.name %>_dependencies" class="dependencies" name="dependencies[]" multiple="multiple" data-placeholder="Choose a dependency">
          <% (@index.apps - [app.name.to_s]).each do |dependency| %>
              <option<%= " selected='selected'" if app.dependencies.include?(dependency) %>><%= dependency %></option>
          <% end %>
        </select>
        <%= hidden_field_tag "dependencies[]", "" %>
    <% end %>
  </td>

  <td>
    <%= form_tag app_path(app.name), :class => "whitelist_form", :method => :put, :remote => true do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <label>CORS Whitelist (comma separated)</label>
        <br>
        <%= text_area_tag('whitelist', app.whitelist.join(",\n"), rows: 5) %>
        <br>
        <%= submit_tag('Update CORS') %>
    <% end %>
  </td>

</tr>

app/views/apps/index.html.erb
<h2>Apps</h2>
<div>
  <%= form_tag apps_path do %>
      <input name="name" placeholder="App name" />
      <button>Add App</button>
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped">
    <% @apps.each do |app| %>
      <%= render 'app', :app => app %>
    <% end %>
  </table>
</div>

<% content_for :onready do %>
  $("select.dependencies").chosen({no_results_text: "No dependencies matched"});

  $("select, input.maintenance").change(function() {
    $(this).closest("form").submit();
  });
<% end %>