config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "apps#index"

  resources :upstreams
  resources :apps, only: %i[index create update destroy]
  resources :vanities, only: %i[index create destroy]
  resources :regexes, only: %i[index create update destroy]
  resources :users, only: %i[index update destroy] do
    collection do
      get :no_access
    end
  end

  get "monitors/lb" => "monitors#lb"

  resource :sessions, only: %i[new destroy]
  get "auth/oktaoauth/callback", to: "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout, :via => [:get, :post, :delete]
end

app/models/vanity.rb
# frozen_string_literal: true

class Vanity
  attr_reader :path, :target, :redis

  def initialize(path, target = nil)
    @redis = redis || Redis.current
    raise Index::NoredisInstance unless @redis

    @path = path
    @existing_target = redis.get(vanity_key)
    @target = if @existing_target
      # Update if values were passed in. otherwise return existing
      target || @existing_target
    else
      target
    end

    self
  end

  def save
    unless @existing_target
      AuditEntry.create!(change_type: "add_vanity",
        key: vanity_key,
        to_value: target,
        user_id: Thread.current[:user_id])
    end
    if @existing_target && target != @existing_target
      AuditEntry.create!(change_type: "update_vanity",
        key: vanity_key,
        from_value: @existing_target,
        to_value: target,
        user_id: Thread.current[:user_id])
    end
    redis.set(vanity_key, target)
  end

  def destroy
    redis.del(vanity_key)
    AuditEntry.create!(change_type: "remove_vanity",
      key: vanity_key,
      from_value: target,
      user_id: Thread.current[:user_id])
  end

  def self.all
    keys = Redis.current.keys("redirect:*").collect { |k|
      k.sub("redirect:", "")
    }

    keys.sort.collect { |k| Vanity.new(k) }
  end

  def created_at
    create_audit.try(:created_at)
  end

  def created_by
    create_audit.try(:user)
  end

  def updated_at
    update_audit.try(:created_at)
  end

  def updated_by
    update_audit.try(:user)
  end

  def create_audit
    @create_audit ||= AuditEntry.includes(:user).find_by(change_type: "add_vanity", key: vanity_key)
  end

  def update_audit
    @update_audit ||= AuditEntry.includes(:user)
      .where(change_type: "update_vanity", key: vanity_key)
      .order("created_at desc").first
  end

  def vanity_key
    "redirect:#{path}"
  end

  def to_partial_path
    "vanity"
  end
end

app/controllers/vanities_controller.rb
# frozen_string_literal: true

class VanitiesController < ApplicationController
  def index
    @vanities = Vanity.all
  end

  def create
    vanity = Vanity.new(params[:path], params[:target])
    vanity.save

    redirect_to vanities_path
  end

  def destroy
    vanity = Vanity.new(Base64.decode64(params[:id]))
    vanity.destroy

    redirect_to vanities_path
  end
end

app/views/vanities/_vanity.html.erb
<tr>
  <td><%= vanity.path %></td>
  <td><%= vanity.target %></td>
  <td>
    <%= form_tag vanity_path(Base64.encode64(vanity.path)), method: :delete,
                       data: { confirm: "Are you sure you want to remove #{vanity.path}?" } do %>
        <button>remove</button>
    <% end %>
  </td>
</tr>

app/views/vanities/index.html.erb
<h2>Vanity Redirects</h2>
<div>
  <%= form_tag vanities_path, id: 'add_vanity_form' do %>
      <input class="path" name="path" placeholder="from path" />
      <input class="target" name="target" placeholder="target path" />
      <button>Add Vanity</button>
  <% end %>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Path</th>
        <th>Target</th>
      </tr>
    </thead>
    <tbody>
      <%= render @vanities %>
    </tbody>
  </table>
</div>